//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShysterWatch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShysterWatch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB1 0AA
        ///AB10 1AA
        ///AB11 3AG
        ///AB12 3AB
        ///AB13 0AA
        ///AB14 0AB
        ///AB15 4AA
        ///AB16 5AB
        ///AB2 0AA
        ///AB21 0AA
        ///AB22 8AA
        ///AB23 8AA
        ///AB24 1AQ
        ///AB25 1AD
        ///AB3 1AA
        ///AB30 1AA
        ///AB31 3AA
        ///AB32 6AA
        ///AB33 8AA
        ///AB34 4JA
        ///AB35 5AT
        ///AB36 8TG
        ///AB37 9AA
        ///AB38 7AA
        ///AB39 2AA
        ///AB4 0AA
        ///AB41 0AA
        ///AB42 0AA
        ///AB43 1AB
        ///AB44 1AA
        ///AB45 1AA
        ///AB5 0AA
        ///AB51 0AA
        ///AB52 6AB
        ///AB53 4AA
        ///AB54 4AA
        ///AB55 3AA
        ///AB56 1AA
        ///AB9 1AA
        ///AB99 8AA
        ///AL1 1AA
        ///AL10 0AA
        ///AL2 1AA
        ///AL3 4AA
        ///AL4 0AA
        ///AL5 1AA
        ///AL6 0AA
        ///AL7 1AA
        ///AL8 6AA
        ///AL9 5AA
        ///B1 1AA
        ///B10 0AA
        ///B11 1AA
        ///B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PostcodesOnePerArea {
            get {
                return ResourceManager.GetString("PostcodesOnePerArea", resourceCulture);
            }
        }
    }
}
