//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShysterWatch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z:\\Good Thinking Society Data\\Compliance Monitor")]
        public string RootFolder {
            get {
                return ((string)(this["RootFolder"]));
            }
            set {
                this["RootFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Members.xml")]
        public string MemberDataFilename {
            get {
                return ((string)(this["MemberDataFilename"]));
            }
            set {
                this["MemberDataFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Websites.xml")]
        public string WebsiteDataFilename {
            get {
                return ((string)(this["WebsiteDataFilename"]));
            }
            set {
                this["WebsiteDataFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Society of Homeopaths")]
        public string SelectedDataSource {
            get {
                return ((string)(this["SelectedDataSource"]));
            }
            set {
                this["SelectedDataSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Search_LastTerm {
            get {
                return ((string)(this["Search_LastTerm"]));
            }
            set {
                this["Search_LastTerm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int WebsitePageLimit {
            get {
                return ((int)(this["WebsitePageLimit"]));
            }
            set {
                this["WebsitePageLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Abdominal aortic aneurysm\r\nAcne\r\nAcute cholecystitis\r\nAcute lymphoblastic leukaem" +
            "ia\r\nAcute myeloid leukaemia\r\nAcute pancreatitis\r\nAddison\'s disease\r\nAlcohol-rela" +
            "ted liver disease\r\nAllergic rhinitis\r\nAllergies\r\nAlzheimer\'s disease\r\nAnal cance" +
            "r\r\nAnaphylaxis\r\nAngioedema\r\nAnkylosing spondylitis\r\nAnorexia nervosa\r\nAnxiety\r\nA" +
            "nxiety disorders in children\r\nAppendicitis\r\nArthritis\r\nAsbestosis\r\nAsthma\r\nAtopi" +
            "c eczema\r\nAttention deficit hyperactivity disorder|ADHD\r\nAutistic spectrum disor" +
            "der|ASD\r\nBacterial vaginosis\r\nBenign prostate enlargement\r\nBile duct cancer|chol" +
            "angiocarcinoma\r\nBinge eating\r\nBipolar disorder\r\nBladder cancer\r\nBlood poisoning|" +
            "sepsis\r\nBone cancer\r\nBowel cancer\r\nBowel incontinence\r\nBowel polyps\r\nBrain stem " +
            "death\r\nBrain tumour\r\nBreast cancer\r\nBronchiectasis\r\nBronchitis\r\nBulimia\r\nBunion\r" +
            "\nCarcinoid syndrome and carcinoid tumours\r\nCatarrh\r\nCellulitis\r\nCervical cancer\r" +
            "\nChest infection\r\nChest pain\r\nChickenpox\r\nChilblains\r\nChronic fatigue syndrome\r\n" +
            "Chronic kidney disease\r\nChronic lymphocytic leukaemia\r\nChronic myeloid leukaemia" +
            "\r\nChronic obstructive pulmonary disease\r\nChronic pancreatitis\r\nCirrhosis\r\nClostr" +
            "idium difficile\r\nCoeliac disease\r\nCold sore\r\nComa\r\nCommon cold\r\nCommon heart con" +
            "ditions\r\nCongenital heart disease\r\nConjunctivitis\r\nConstipation\r\nCoronavirus|COV" +
            "ID|SARS\r\nCough\r\nCrohn\'s disease\r\nCroup\r\nCystic fibrosis\r\nCystitis\r\nDeafblindness" +
            "\r\nDeep vein thrombosis\r\nDehydration\r\nDementia\r\nDementia with Lewy bodies\r\nDental" +
            " abscess\r\nDepression\r\nDermatitis herpetiformis\r\nDiabetes\r\nDiarrhoea\r\nDiscoid ecz" +
            "ema\r\nDiverticular disease|diverticulitis\r\nDizziness|Lightheadedness\r\nDown\'s synd" +
            "rome\r\nDry mouth\r\nDysphagia|swallowing problems\r\nDystonia\r\nEarache\r\nEarwax build-" +
            "up\r\nEbola virus disease\r\nEctopic pregnancy\r\nEndometriosis\r\nEpilepsy\r\nErectile dy" +
            "sfunction|impotence\r\nEscherichia coli|E. coli\r\nEwing sarcoma\r\nEye cancer\r\nFebril" +
            "e seizures\r\nFever in children\r\nFibroids\r\nFibromyalgia\r\nFlatulence\r\nFlu\r\nFoetal a" +
            "lcohol syndrome\r\nFood poisoning\r\nFungal nail infection\r\nGallbladder cancer\r\nGall" +
            "stones\r\nGanglion cyst\r\nGastroenteritis\r\nGastro-oesophageal reflux disease|GORD\r\n" +
            "Genital herpes\r\nGenital warts\r\nGerm cell tumours\r\nGlandular fever\r\nGout\r\nGum dis" +
            "ease\r\nHaemorrhoids|piles\r\nHairy cell leukaemia\r\nHand, foot and mouth disease\r\nHa" +
            "y fever\r\nHead and neck cancer\r\nHead lice and nits\r\nHeadaches\r\nHearing loss\r\nHear" +
            "t failure\r\nHepatitis A\r\nHepatitis B\r\nHepatitis C\r\nHiatus hernia\r\nHigh cholestero" +
            "l\r\nHIV\r\nHodgkin lymphoma\r\nHuntington\'s\r\nHyperglycaemia|high blood sugar\r\nHyperhi" +
            "drosis\r\nHypoglycaemia|low blood sugar\r\nIdiopathic pulmonary fibrosis\r\nImpetigo\r\n" +
            "Indigestion\r\nIngrown toenail\r\nInherited heart conditions\r\nInsomnia\r\nIron deficie" +
            "ncy anaemia\r\nIrritable bowel syndrome|IBS\r\nIrritable hip\r\nItching\r\nItchy bottom\r" +
            "\nKaposi\'s sarcoma\r\nKidney cancer\r\nKidney infection\r\nKidney stones\r\nLabyrinthitis" +
            "\r\nLactose intolerance\r\nLangerhans cell histiocytosis\r\nLaryngeal cancer|larynx ca" +
            "ncer\r\nLaryngitis\r\nLeg cramps\r\nLichen planus\r\nLiver cancer\r\nLiver disease\r\nLiver " +
            "tumours\r\nLoss of libido\r\nLung cancer\r\nLupus\r\nLyme disease\r\nLymphoedema\r\nMalaria\r" +
            "\nMalignant brain tumour|brain tumour\r\nMalnutrition\r\nMeasles\r\nMeningitis\r\nMenopau" +
            "se\r\nMesothelioma\r\nMiddle ear infection|otitis media\r\nMigraine\r\nMiscarriage\r\nMoto" +
            "r neurone disease|MND\r\nMouth cancer\r\nMouth ulcer\r\nMultiple myeloma\r\nMultiple scl" +
            "erosis|MS\r\nMumps\r\nMeniere\'s disease\r\nNasal and sinus cancer\r\nNasopharyngeal canc" +
            "er\r\nNeuroblastoma\r\nNeuroendocrine tumours\r\nNon-alcoholic fatty liver disease|NAF" +
            "LD\r\nNon-Hodgkin lymphoma\r\nNorovirus\r\nNosebleed\r\nObesity\r\nObsessive compulsive di" +
            "sorder|OCD\r\nObstructive sleep apnoea\r\nOesophageal cancer\r\nOral thrush in adults\r" +
            "\nOsteoarthritis\r\nOsteoporosis\r\nOsteosarcoma\r\nOtitis externa\r\nOvarian cancer\r\nOva" +
            "rian cyst\r\nOveractive thyroid\r\nPaget\'s disease of the nipple\r\nPancreatic cancer\r" +
            "\nPanic disorder\r\nParkinson\'s disease\r\nPelvic organ prolapse\r\nPenile cancer\r\nPeri" +
            "pheral neuropathy\r\nPersonality disorder\r\nPleurisy\r\nPneumonia\r\nPolymyalgia rheuma" +
            "tica\r\nPost-traumatic stress disorder|PTSD\r\nPostnatal depression\r\nPregnancy and b" +
            "aby\r\nPressure ulcers\r\nProstate cancer\r\nPsoriasis\r\nPsoriatic arthritis\r\nPsychosis" +
            "\r\nRare tumours\r\nRaynaud\'s phenomenon\r\nReactive arthritis\r\nRestless legs syndrome" +
            "\r\nRetinoblastoma\r\nRhabdomyosarcoma\r\nRheumatoid arthritis\r\nRingworm and other fun" +
            "gal infections\r\nRosacea\r\nScabies\r\nScarlet fever\r\nSchizophrenia\r\nScoliosis\r\nSepti" +
            "c shock\r\nSexually transmitted infections|STIs|STI\r\nShingles\r\nShortness of breath" +
            "\r\nSickle cell disease\r\nSinusitis\r\nSjogren\'s syndrome\r\nSkin cancer|melanoma|non-m" +
            "elanoma\r\nSlapped cheek syndrome\r\nSoft tissue sarcomas\r\nSore throat\r\nSpleen probl" +
            "ems and spleen removal\r\nStillbirth\r\nStomach ache and abdominal pain\r\nStomach can" +
            "cer\r\nStomach ulcer\r\nStress, anxiety and low mood\r\nStroke\r\nSudden infant death sy" +
            "ndrome|SIDS\r\nSuicide\r\nSunburn\r\nSwollen glands\r\nTesticular cancer\r\nTesticular lum" +
            "ps and swellings\r\nThirst\r\nThreadworms\r\nThrush in men\r\nThyroid cancer\r\nTinnitus\r\n" +
            "Tonsillitis\r\nTooth decay\r\nToothache\r\nTransient ischaemic attack|TIA\r\nTrigeminal " +
            "neuralgia\r\nTuberculosis|TB\r\nType 1 diabetes\r\nType 2 diabetes\r\nUlcerative colitis" +
            "\r\nUnderactive thyroid\r\nUrinary incontinence\r\nUrinary tract infection|UTI\r\nUrtica" +
            "ria|hives\r\nVaginal cancer\r\nVaginal thrush\r\nVaricose eczema\r\nVaricose veins\r\nVeno" +
            "us leg ulcer\r\nVertigo\r\nVitamin B12 or folate deficiency anaemia\r\nVomiting in adu" +
            "lts\r\nVulval cancer\r\nWarts and verrucas\r\nWhooping cough\r\nWilms\' tumour\r\nWomb canc" +
            "er|uterus cancer|uteral cancer|endometrial cancer|uterine cancer\r\nYellow fever")]
        public string SearchTerms {
            get {
                return ((string)(this["SearchTerms"]));
            }
            set {
                this["SearchTerms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter it here!")]
        public string OpenAIApiKey {
            get {
                return ((string)(this["OpenAIApiKey"]));
            }
            set {
                this["OpenAIApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int AiPromptSpecificationReference {
            get {
                return ((int)(this["AiPromptSpecificationReference"]));
            }
            set {
                this["AiPromptSpecificationReference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2023-12-20")]
        public global::System.DateTime RelevantDateForChoosingVersion {
            get {
                return ((global::System.DateTime)(this["RelevantDateForChoosingVersion"]));
            }
            set {
                this["RelevantDateForChoosingVersion"] = value;
            }
        }
    }
}
